import Boolean

fun main(){
 val misol=Misol()
    misol.begin3()
    val integer=Integer()
    integer.inte1(15)
    val w=When()
    w.ven(7)
   val kvadrat=Kvadrat(4)
   kvadrat.Peremetri()
   kvadrat.Yuzasi()
    val togriTortburchak=TogriTortburchak(5,6)
    togriTortburchak.Peremetri()
    togriTortburchak.Yuzasi()
    val aylana=Aylana(8)
    aylana.Uzunligi()
    val kub=Kub(5)
    kub.Xajmi()
    kub.Yuzi()
    val parallellipiped=Parallellipiped(3,4,5)
    parallellipiped.Xajmi()
    parallellipiped.Yuzi()
    val doira=Doira(7)
    doira.uzunli()
    doira.Yuzasi()
    val oarifmetik=Oarifmetik(10,16)
    oarifmetik.Arifmetik()
    val integer1=Integer1(3000,1000)
    integer1.sm()
    integer1.t()
    val case=Case(5)
    case.hf()


    val dataL=DataL(5,"Android")
    val dataL2=DataL("Oliy",21)
    val dataL3=DataL(750)
    val dataL4=DataL(50,"Zor")
    dataL.data()
    dataL2.data2()
    dataL3.data3()
    dataL4.data4()

}